import arrows

INSERT_COMPUTER = True

game = arrows.Map()
for i in range(8):
    game.set(0, 38 + i, arrows.Arrow(type=arrows.ArrowType.Source))

commands = "+-<>[].,"
COMMAND_BLOCK = "AAAEAAAAAAAKAU4AARADIAEwA3ACkAMBAREDMQNxA4EAkQChALED0QPxABICIgIyAkICUgJiAnICggKSAqICsgLiAvICIwHjAPMAFAMkATQD5AD0ABUDJQE1A4UBlQClALUAFgM2A0YAVgBmAHYAhgCmArYC5gL2AgcBFwMnADcDVwBnAHcAhwCXA7cAxwDXAwgBGAM4A0gCWAJoAngCmAOoArgC6AL4AgoUgALwAyEBwQDCAgMBEwMzA8MDBQHVAPUAJgHGAkcApwDnAPcAiALIAtgDEAKgAOEA0wMPALAADgLAANIH1AcHAdADAgEDAMQDDADFAw0B5QQoBgYAlgALANYCAAABAAoBOAAAQAGAApACoALAAdAA4ADwAwEAEQAhAPEDMgGiA7IB8gEDAEMCswHTAOMA8wAEAxQAJADUAOQA9AAFAHUAhQAGAhYCJgI2AkYCVgKGApYCpgK2AsYC1gLmAggCGAI4AUgCWAKIApgCqAK4AsgC2AL4AxAEEABQAGEDgwFlAQorMAGwAUEBcQCRAKEAsQASA0ICUgFiAnIAEwEzAFMCYwOTAMMAhAGkA8QAlQC1AGYCdgH2AgcAFwEnAEcAVwBnAHcAhwCXAKcAtwDHANcA5wD3ACgCaALoAg4EYABwAHMFtAF4AQ8DMQDBADQAZAENA1EEIgZ0BTcACwGBAFQCDAECAqMABwGCARUAAwKSASMCxQAFAEQAAAACAAwKDgAAUQBSABQAZQF1AYUBlQGlAbUBxQHVATcAGAJIAwEcEAAgAjACQAEhAUEBYQBxAIEAkQChALEAIgFCAaIAsgMTASMBQwEEAyQBRAEFAyYBFwAnAQgCKAE4AhkZUABgAHAAgACQAKAAsADAANAA4ADwAMEA0QDhAMIA0gDiAFMA4wBUAOQAVQDlAOYA5wDoABALAQACAGQBdAGEAZQBpAG0AcQB1AFGAEcABwsRAxIANgNXAGcAdwCHAJcApwC3AMcA1wAMAjEAMgADAwUEYgByAIIAkgBWAhgANAIDAhUAJQE1AhMARQEOAAYHCwkWAVgDaAN4A4gDmAOoA7gDyAPYAw0IZgd2B4YHlgemB7YHxgfWBwcEAAADAAAZAQAAEAA="
END_BLOCK = "AAALAAAAAAAAGY8AABAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAAEAEQAhADEAQQBRAGEAcQCBAJEAoQCxAMEA0QDhAPEAAgASACIAMgBCAFIAYgByAIIAkgCiALIAwgDSAOIA8gADABMAIwAzAEMAUwBjAHMAgwCTAKMAswDDANMA4wDzAAQAFAAkADQARABUAGQAdACEAJQApAC0AMQA1ADkAPQABQAVACUANQBFAFUAZQB1AIUAlQClALUAxQDVAOUA9QAGABYAJgA2AEYAVgBmAHYAhgCWAKYAtgDGANYA5gD2AAcAFwAnADcARwBXAGcAdwCHAJcApwC3AMcA1wDnAPcACAAYACgAOABIAFgAaAB4AIgAmACoALgAyADYAOgA+AAAAAEAABmPAAAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AABABEAIQAxAEEAUQBhAHEAgQCRAKEAsQDBANEA4QDxAAIAEgAiADIAQgBSAGIAcgCCAJIAogCyAMIA0gDiAPIAAwATACMAMwBDAFMAYwBzAIMAkwCjALMAwwDTAOMA8wAEABQAJAA0AEQAVABkAHQAhACUAKQAtADEANQA5AD0AAUAFQAlADUARQBVAGUAdQCFAJUApQC1AMUA1QDlAPUABgAWACYANgBGAFYAZgB2AIYAlgCmALYAxgDWAOYA9gAHABcAJwA3AEcAVwBnAHcAhwCXAKcAtwDHANcA5wD3AAgAGAAoADgASABYAGgAeACIAJgAqAC4AMgA2ADoAPgAAAACAAMZfgAAEAAwAEAAUABgAHAAgACQAKAAsADAANAA4AABABEAMQBRAHEAkQCxANEAAgASACIAMgBCAFIAYgByAIIAkgCiALIAwgDSAOIAAwATACMAMwBDAFMAYwBzAIMAkwCjALMAwwDTAOMABAAUACQANABEAFQAZAB0AIQAlACkALQAxADUAOQABQAVACUANQBFAFUAZQB1AIUAlQClALUAxQDVAOUABgAWACYANgBGAFYAZgB2AIYAlgCmALYAxgDWAOYABwAXACcANwBHAFcAZwB3AIcAlwCnALcAxwDXAOcACAAYACgAOABIAFgAaAB4AIgAmACoALgAyADYAOgAAQAgAQoGIQJBAmECgQKhAsEC8QIMAOECAAADAAMBQgECUQJhAnECgQKRAqECsQLBAtEC4QLxAkICUgJiAnICggKSAqIBsgHSAOIA8gCTAaMAwwLTAYQBlADUAuQBdQGFAOUC9QFmAXYA9gJXAWcASAFYAEkBiwGbAKsAuwDLANsA6wBsAXwAnACsALwAzADcAPwAXQF9AI0A7QD9AE4BbgBPAV8BEgARAhEBIQIxAgcFQQHCAIwA7ANtAF4AAAAEAAIBEQECEQIhAQIAEgAiAAYBBwIXARgCKAEpAQwADgAeAC4AHwMvAxEDKgErASwBLQAHAQ0DHQABAAMAAwFNQAJgAVECcQKBAuEC8QJiAnICkgKiArICwgLSAvICgwKTAqMCwwLTAuMDRgFWAGYAdgCGAJYApgDGAtYC5gL2AkcCVwJnAncChwKXAqcBtwHHANcA5wD3AKgBuAGpAbkBqgG6AasBuwGsAbwBTQFdAG0AfQCNAJ0ArQC9As0C3QLtAv0CTgJeAm4CfgKOAp4CrgK+Ac4A3gDuAP4ABwRQAWEBggHiArMBEQK0AbUBvwEGALYAAQAEAAEBDwACIAMRAwIDBgIWAiYBBwAXACcADQIdAi0BDgAeAC4ABwEQAgECAgADAAIRALABAURBAVEAYQBxAIEAkQChAMEC0QLhAvECQgFSAmICcgKCApICogGyAcIA0gDiAPIAQwFTA6MBswFEAVQDpAG0AUUBVQOlAbUBRgFWA6YBtgFHAVcDpwG3AUgCWANMAVwAbAB8AIwAnACsALwAzADcAOwA/ABNAl0CbQJ9Ao0CnQKtAr0CzQLdAu0C/QIGALEAAgAEAAIBGgECEQIhAQIAEgAiARMDIwEUAyQBFQMlARYDJgEXAycBGAMMABwALAANAh0BLQMeAS4DHwEvAwcAKAARAikBKgErAQMABAAAARMQASADEQEhAxIBIgMDABMAIwMEAhQBJAMVASUDNQBFABYCJgI2AkYDAwADAAABF0MBUwBjAHMAgwCTAKMAswDDANMA4wDzAEQCVAJkAnQChAKUAqQCtALEAtQC5AL0Ag=="

filename = input("Название файла brainfuck: ")

with open(filename, "r") as file:
    i = 0
    while True:
        symbol = file.read(1)
        if symbol == "":
            break
        symbol_num = commands.find(symbol)
        if symbol_num == -1:
            continue
        print(symbol, end="")
        for j in range(8):
            if j == symbol_num:
                arrow = arrows.ArrowType.Source
            else:
                arrow = arrows.ArrowType.Pulse
            game.set(5 + i * 9, 38 + j, arrows.Arrow(type=arrow))
        if INSERT_COMPUTER:
            game.import_(COMMAND_BLOCK, 2 + i * 9)
        i += 1
    if INSERT_COMPUTER:
        game.import_(END_BLOCK, 2 + i * 9)

print("\n")
print(f"Количество команд: {i}")

with open(f"{filename}.txt", "w") as file:
    file.write(game.export())
