import arrows

INSERT_COMPUTER = True

game = arrows.Map()
for i in range(8):
    game.set(0, 33 + i, arrows.Arrow(type=arrows.ArrowType.Source))

commands = "+-<>[].,"
COMMAND_BLOCK = "AAADAAAAAAAKCjYAASABUALAAxEDMQORANEA8QASAiIBMgJSAnICkgLiAwMBEwMzA5MD4wEkAfQABQEVAzUDhQClAMUAJgFWAHYClgK2AtYC9gIHARcDRwB3AJcAtwDHANcA5wH3ADgDWAJoA3gCmAKoA7gC2AL4AgEVQAJgA9AAQQNRAGEAcQCBA6EDsgLCArMAwwC0ANUANgPmAicAVwCnAxgDSAIQA3AA4ACxAKMDDwCAAA4CkACiB6QHBwKgAwIB5QAMAdIClQMNAvIGtQQoBgMB8wKUAwsC1ANlAKYCBgBmAAAAAQAMCjYAAWACgAGwANAC8AERAUEAYQBxAIEAoQMSAiIBMgJCAIIB8gEDACMCMwNjAJMA0wFUAXQDlADEALUDFgI2AkYBZgKGAqYCFwAnADcARwBXAGcAdwCHAJcApwDXAecAGAI4AlgCeAKYArgC2AL4AwEUEAFQApABwADRAQIBcgPSARMCpAD0AUUAVQBlAHUAhQBWAtYBxwAIAagDEAcgADEDsQCyAFMBNQH2APcADgUwAEAAQwWEAbYHSAEPAwEAkQAEADQBDQQhBMIFRAUHALcECwNRAKIAJALGAQcCwQNSAeYDDAPhAOIAcwCzAwMEYgGVAMUA1QHlAgUAFAAYAOQCEwD1AQAAAgAHGQGQAKAACgkBAAIAFQElATUBRQFVAWUBdQGFAQEFEQAhADEAQQBRAFIABQQSACIAMgBCAAYCCwliAwgDGAMoAzgDSANYA2gDeAOIAxAHFAEkATQBRAFUAWQBdAGEAQ0HFgcmBzYHRgdWB2YHdgeGBwcIBwAXACcANwBHAFcAZwB3AIcA"
END_BLOCK = "AAALAAAAAAAAGY8AABAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAAEAEQAhADEAQQBRAGEAcQCBAJEAoQCxAMEA0QDhAPEAAgASACIAMgBCAFIAYgByAIIAkgCiALIAwgDSAOIA8gADABMAIwAzAEMAUwBjAHMAgwCTAKMAswDDANMA4wDzAAQAFAAkADQARABUAGQAdACEAJQApAC0AMQA1ADkAPQABQAVACUANQBFAFUAZQB1AIUAlQClALUAxQDVAOUA9QAGABYAJgA2AEYAVgBmAHYAhgCWAKYAtgDGANYA5gD2AAcAFwAnADcARwBXAGcAdwCHAJcApwC3AMcA1wDnAPcACAAYACgAOABIAFgAaAB4AIgAmACoALgAyADYAOgA+AAAAAEAAhmNAAAQACAAMABAAFAAYABwAIAAkACgALAAwADgAPAAAQARACEAMQBBAFEAYQBxAIEAkQChALEAwQDRAPEAAgASACIAMgBCAFIAYgByAIIAkgCiALIAwgDSAOIA8gADABMAIwAzAEMAUwBjAHMAgwCTAKMAswDDANMA4wDzAAQAFAAkADQARABUAGQAdACEAJQApAC0AMQA1ADkAPQABQAVACUANQBFAFUAZQB1AIUAlQClALUAxQDVAOUA9QAGABYAJgA2AEYAVgBmAHYAhgCWAKYAtgDGANYA5gD2AAcAFwAnADcARwBXAGcAdwCHAJcApwC3AMcA1wDnAPcACAAYACgAOABIAFgAaAB4AIgAmACoALgAyADYAOgA+AALANABCgDhAgAAAgACGX4AABAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4AARADEAUQBxAJEAsQDRAAIAEgAiADIAQgBSAGIAcgCCAJIAogCyAMIA0gDiAAMAEwAjADMAQwBTAGMAcwCDAJMAowCzAMMA0wDjAAQAFAAkADQARABUAGQAdACEAJQApAC0AMQA1ADkAAUAFQAlADUARQBVAGUAdQCFAJUApQC1AMUA1QDlAAYAFgAmADYARgBWAGYAdgCGAJYApgC2AMYA1gDmAAcAFwAnADcARwBXAGcAdwCHAJcApwC3AMcA1wDnAAgAGAAoADgASABYAGgAeACIAJgAqAC4AMgA2ADoAAoHAQIhAkECYQKBAqECwQLxAgwA4QIAAAMAAwFCAQJRAmECcQKBApECoQKxAsEC0QLhAvECQgJSAmICcgKCApICogGyAdIA4gDyAJMBowDDAtMBhAGUANQC5AF1AYUA5QL1AWYBdgD2AlcBZwBIAVgASQGLAZsAqwC7AMsA2wDrAGwBfACcAKwAvADMANwA/ABdAX0AjQDtAP0ATgFuAE8BXwESABECEQEhAjECBwVBAcIAjADsA20AXgAAAAQAAgERAQIRAiEBAgASACIABgEHAhcBGAIoASkBDAAOAB4ALgAfAy8DEQMqASsBLAEtAAcBDQMdAAEAAwADAU1AAmABUQJxAoEC4QLxAmICcgKSAqICsgLCAtIC8gKDApMCowLDAtMC4wNGAVYAZgB2AIYAlgCmAMYC1gLmAvYCRwJXAmcCdwKHApcCpwG3AccA1wDnAPcAqAG4AakBuQGqAboBqwG7AawBvAFNAV0AbQB9AI0AnQCtAL0CzQLdAu0C/QJOAl4CbgJ+Ao4CngKuAr4BzgDeAO4A/gAHBFABYQGCAeICswERArQBtQG/AQYAtgABAAQAAQEPAAIgAxEDAgMGAhYCJgEHABcAJwANAh0CLQEOAB4ALgAHARACAQICAAMAAhEAsAEBREEBUQBhAHEAgQCRAKEAwQLRAuEC8QJCAVICYgJyAoICkgKiAbIBwgDSAOIA8gBDAVMDowGzAUQBVAOkAbQBRQFVA6UBtQFGAVYDpgG2AUcBVwOnAbcBSAJYA0wBXABsAHwAjACcAKwAvADMANwA7AD8AE0CXQJtAn0CjQKdAq0CvQLNAt0C7QL9AgYAsQACAAQAAgEaAQIRAiEBAgASACIBEwMjARQDJAEVAyUBFgMmARcDJwEYAwwAHAAsAA0CHQEtAx4BLgMfAS8DBwAoABECKQEqASsBAwAEAAABExABIAMRASEDEgEiAwMAEwAjAwQCFAEkAxUBJQM1AEUAFgImAjYCRgMDAAMAAAEXQwFTAGMAcwCDAJMAowCzAMMA0wDjAPMARAJUAmQCdAKEApQCpAK0AsQC1ALkAvQC"

filename = input("Название файла brainfuck: ")

with open(filename, "r") as file:
    i = 0
    while True:
        symbol = file.read(1)
        if symbol == "":
            break
        symbol_num = commands.find(symbol)
        if symbol_num == -1:
            continue
        print(symbol, end="")
        for j in range(8):
            if j == symbol_num:
                arrow = arrows.ArrowType.Source
            else:
                arrow = arrows.ArrowType.Pulse
            game.set(5 + i * 9, 33 + j, arrows.Arrow(type=arrow))
        if INSERT_COMPUTER:
            game.import_(COMMAND_BLOCK, 2 + i * 9)
        i += 1
    if INSERT_COMPUTER:
        game.import_(END_BLOCK, 2 + i * 9)

print("\n")
print(f"Количество команд: {i}")

with open(f"{filename}.txt", "w") as file:
    file.write(game.export())
